# Generated by Django 5.2.4 on 2025-07-27 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.project'),
        ),
        migrations.AddField(
            model_name='worktype',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='work_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worktype',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='projects.estimate'),
        ),
    ]
