# Generated by Django 5.2.4 on 2025-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('project', 'Проект'), ('employee', 'Сотрудник'), ('warehouse', 'Склад'), ('custom', 'Произвольный')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
    ]
